### ISSUE TITLE
add imageset to iOS Application

### ISSUE THREAD

**Issue by jigt-gft** [fdzsergio/BazelSample#1]
Hi,

We are having a problem when adding the imageset to an Ios application in bazel.

Please could you help us to add the imageset, launchScreen and image Assests to the ios_application node of the BUILD file?

best regards.

**Comment by fdzsergio** [comment]
Hi,

In the [rules_apple](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application) doc, you had the description of all parameters for `ios_application` function. If you need to add a custom `launch_storyboard` maybe you need to specify the filepath to the `ios_application` and exclude from other assets. 

You can see an example on [App/Resources/BUILD](https://github.com/fdzsergio/BazelSample/blob/master/App/Resources/BUILD) file when exclude de `appiconset` for *Assets* rule.
